### PR TITLE
EntityAI 

### PR DESCRIPTION
**Pull request by NycuRO**
Thanks @boy0001 for your creation! <3

Created by @boy0001 and edited by @NycuRO.

Values from PureEntities and PureEntitiesX.

### CODE REVIEW

**Comment by jrodr10** [comment]
Errors?

src/main/java/cn/nukkit/entity/item/EntityMinecartChest.java 
src/main/java/cn/nukkit/math/BlockVector3.java 
src/main/java/cn/nukkit/math/Vector3.java 

or just warnings

**Comment by NycuRO** [comment]
@jrodr10 This branch is for testing.

**Comment by jrodr10** [comment]
why was this closed....

**Comment by NycuRO** [comment]
@jrodr10 EntityAl by boy isn't ok, have bug visual and other. I implement other Entity Al @jrodr10

**Pull request closed without merging**
